spring.application.name=taller

#Reemplazar ${MONGODB_URI} por lo que indica el .env
spring.mongodb.uri=${MONGODB_URI}

# Use PORT provided by hosting platforms (default 8080)
server.port=${PORT:8080}